#pragma once
#include "../graphics/opengl.h"

typedef enum mouse_cursors_e {
    MOUSE_CURSOR_NORMAL = GLFW_ARROW_CURSOR,
    MOUSE_CURSOR_POINTER = GLFW_POINTING_HAND_CURSOR,
    MOUSE_CURSOR_BEAM = GLFW_IBEAM_CURSOR,
    MOUSE_CURSOR_CROSSHAIR = GLFW_CROSSHAIR_CURSOR,
    MOUSE_CURSOR_HAND = GLFW_HAND_CURSOR,
    MOUSE_CURSOR_HRESIZE = GLFW_HRESIZE_CURSOR,
    MOUSE_CURSOR_VRESIZE = GLFW_VRESIZE_CURSOR,
    MOUSE_CURSOR_NWSE = GLFW_RESIZE_NWSE_CURSOR,
    MOUSE_CURSOR_SWNE = GLFW_RESIZE_NESW_CURSOR,
} mouse_cursors_e;